### PR TITLE
Chore update phoenix html

### PR DESCRIPTION
**Pull request by tmaszk**
Use `phoenix_html_helpers` to support `phoenix_html` version 4 as specified in the [phoenix_html changelog](https://github.com/phoenixframework/phoenix_html/blob/main/CHANGELOG.md#v400-2023-12-19).

### CODE REVIEW

**Review by tfwright — CHANGES_REQUESTED** [review]
This looks great.  Though it looks like you may have updated all deps rather than just phoenix_html? I would prefer just to update the deps necessary to make the jump to phoenix_html 4.0. If you can make that change and squash everything down to a single commit I can merge

**Comment by tmaszk** [comment]
@tfwright I rebased my commit on the latest main and removed all unnecessary package updates.  Several of the phoenix packages and a few of their dependencies had to be updated.

**Comment by tfwright** [comment]
@tmaszk perfect! just need to squash to single commit and we're good to go. No need to keep adding and using the package separate I don't think :)

**Comment by tmaszk** [comment]
@tfwright rebased and squashed

**Comment by tmaszk** [comment]
This should resolve #98

**Pull request merged**
