### PR TITLE
Updates for LiveView 0.18.x

### PR DESCRIPTION
**Pull request by harmon25**
Biggest change between 0.17 -> 0.18 seems to be moving some functions around.

assigns + assigns new now belong to `Phoenix.Component` instead of `Phoenix.LiveView`

this change addresses that, but there are still some new warnings warnings, all tests are passing

### CODE REVIEW

**Comment by jmillxyz** [comment]
Hi there! I was going to open a similar PR, any chance of getting this merged to fix warnings for LiveView 0.18 installations?

**Comment by tfwright** [comment]
Hi @jmillxyz Not sure exactly how close this is to being ready. It doesn't look like there have been any recent changes, but I wanted to check into possible backwards compatibility before merging. 

Are you using a current release of LiveAdmin with LiveView 0.18? Have you run into any issues besides warnings?

**Comment by jmillxyz** [comment]
I'm using a branch of LiveAdmin 0.5 with one LiveView 0.18.11 app, and a branch of LiveAdmin 0.6 for another. Admittedly I'm not making use of all of LiveAdmin's features (e.g. not using `prefix_options`, or most of the resource-specific options), mostly as a simple DB viewer.

IIRC LiveAdmin won't actually compile because of some of the changes in LV 0.18, like the `Phoenix.Component` change @harmon25 mentioned.

**Comment by tfwright** [comment]
[0.7](https://github.com/tfwright/live_admin/releases/tag/v0.7) has been released with support for LV 0.18

**Pull request closed without merging**
